/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteFerArgs } from "./DeleteFerArgs";
import { FerFindManyArgs } from "./FerFindManyArgs";
import { FerFindUniqueArgs } from "./FerFindUniqueArgs";
import { Fer } from "./Fer";
import { FerService } from "../fer.service";

@graphql.Resolver(() => Fer)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FerResolverBase {
  constructor(
    protected readonly service: FerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Fer",
    action: "read",
    possession: "any",
  })
  async _fersMeta(
    @graphql.Args() args: FerFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Fer])
  @nestAccessControl.UseRoles({
    resource: "Fer",
    action: "read",
    possession: "any",
  })
  async fers(@graphql.Args() args: FerFindManyArgs): Promise<Fer[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Fer, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Fer",
    action: "read",
    possession: "own",
  })
  async fer(@graphql.Args() args: FerFindUniqueArgs): Promise<Fer | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Fer)
  @nestAccessControl.UseRoles({
    resource: "Fer",
    action: "delete",
    possession: "any",
  })
  async deleteFer(@graphql.Args() args: DeleteFerArgs): Promise<Fer | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
